server:
  port: 10086

#Eureka的配置
eureka:
  instance:
    appname: springcloud-eureka  #Eureka服务端的实例名称(如果配置集群，此处不能写localhost或127.0.0.1)
  client:
    register-with-eureka: true # 表示是否想eureka注册中心相互注册
    fetch-registry: true  #默认为true  表示自己为注册中心
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/