server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_user?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ

mybatis:
  type-aliases-package: com.angryzyh.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.angryzyh: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
